source 'https://github.com/CocoaPods/Specs.git'

platform :tvos, "10.0"
use_frameworks!
inhibit_all_warnings!

target 'RNAppleTVNavigation' do
  react_native_path = '../node_modules/react-native'
  pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'DevSupport',
    'CxxBridge',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTText',
    'RCTSettings',
    'RCTPushNotification',
    'RCTAnimation',
    'RCTLinkingIOS',
    'RCTImage'
  ]
  pod 'yoga', :path => react_native_path + '/ReactCommon/yoga'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => react_native_path + '/third-party-podspecs/glog.podspec'

  pod 'RNSVG', :path => react_native_path + '/../react-native-svg'
end

# When using RN in combination with Cocoapods, a lot of 
# things are broken. These are the fixes we had to append 
# to our Podfile when upgrading to ReactNative@0.55.3.
# 
# WARNING: Check those line numbers when you're on a different version!

def change_lines_in_file(file_path, &change)
  print "Fixing #{file_path}...\n"

  contents = []

  file = File.open(file_path, 'r')
  file.each_line do | line |
    contents << line
  end
  file.close

  File.open(file_path, 'w') do |f|
    f.puts(change.call(contents))
  end
end


post_install do |installer|
    react_native_path = '../node_modules/react-native'

  # https://github.com/facebook/yoga/issues/711#issuecomment-381098373
  change_lines_in_file('./Pods/Target Support Files/yoga/yoga-umbrella.h') do |lines|
    lines.reject do | line |
      [
        '#import "Utils.h"',
        '#import "YGLayout.h"',
        '#import "YGNode.h"',
        '#import "YGNodePrint.h"',
        '#import "YGStyle.h"',
        '#import "Yoga-internal.h"',
      ].include?(line.strip)
    end
  end

  # https://github.com/facebook/yoga/issues/711#issuecomment-374605785
  change_lines_in_file(react_native_path + '/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h') do |lines|
    unless lines[27].include?("#ifdef __cplusplus")
      lines.insert(27, "#ifdef __cplusplus")
      lines.insert(34, "#endif")
    end
    lines
  end

  # https://github.com/facebook/react-native/issues/13198
  change_lines_in_file(react_native_path + '/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h') do |lines|
    lines.map { |line| line.include?("#import <RCTAnimation/RCTValueAnimatedNode.h>") ? '#import "RCTValueAnimatedNode.h"' : line }
  end

  # https://github.com/facebook/react-native/issues/16039
  change_lines_in_file(react_native_path + '/Libraries/WebSocket/RCTReconnectingWebSocket.m') do |lines|
    lines.map { |line| line.include?("#import <fishhook/fishhook.h>") ? '#import "fishhook.h"' : line }
  end
end
